# Automatically label PRs based on changed files

# Documentation changes
documentation:
  - changed-files:
    - any-glob-to-any-file: 
      - 'README.md'
      - 'docs/**/*'
      - '**/*.md'

# Frontend/UI changes
frontend:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/components/**/*'
      - 'src/pages/**/*'
      - '**/*.jsx'
      - '**/*.tsx'
      - '**/*.css'

# Configuration changes
config:
  - changed-files:
    - any-glob-to-any-file:
      - '*.json'
      - '*.yml'
      - '*.yaml'
      - '.github/**/*'

# CI/CD changes
ci-cd:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'

# Dependencies
dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'package.json'
      - 'package-lock.json'
      - 'pnpm-lock.yaml'
      - 'yarn.lock'
